# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler_to_master.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'scheduler_to_master.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19scheduler_to_master.proto\x1a\x0c\x63ommon.proto\"\"\n\x0fScheduleRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\":\n\x10ScheduleResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\x8e\x01\n\x11SchedulerToMaster\x12\x31\n\x08Schedule\x12\x10.ScheduleRequest\x1a\x11.ScheduleResponse\"\x00\x12#\n\x0f\x42roadcastFinish\x12\x06.Empty\x1a\x06.Empty\"\x00\x12!\n\rTrainingBegin\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_to_master_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCHEDULEREQUEST']._serialized_start=43
  _globals['_SCHEDULEREQUEST']._serialized_end=77
  _globals['_SCHEDULERESPONSE']._serialized_start=79
  _globals['_SCHEDULERESPONSE']._serialized_end=137
  _globals['_SCHEDULERTOMASTER']._serialized_start=140
  _globals['_SCHEDULERTOMASTER']._serialized_end=282
# @@protoc_insertion_point(module_scope)
