# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trainer_to_scheduler.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'trainer_to_scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atrainer_to_scheduler.proto\x1a\x0c\x63ommon.proto\"%\n\x13ReportStableRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\r\"(\n\x12ReportReadyRequest\x12\x12\n\ntrainer_id\x18\x01 \x01(\r2r\n\x12TrainerToScheduler\x12.\n\x0cReportStable\x12\x14.ReportStableRequest\x1a\x06.Empty\"\x00\x12,\n\x0bReportReady\x12\x13.ReportReadyRequest\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trainer_to_scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPORTSTABLEREQUEST']._serialized_start=44
  _globals['_REPORTSTABLEREQUEST']._serialized_end=81
  _globals['_REPORTREADYREQUEST']._serialized_start=83
  _globals['_REPORTREADYREQUEST']._serialized_end=123
  _globals['_TRAINERTOSCHEDULER']._serialized_start=125
  _globals['_TRAINERTOSCHEDULER']._serialized_end=239
# @@protoc_insertion_point(module_scope)
