# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker_to_trainer.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'worker_to_trainer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17worker_to_trainer.proto\x1a\x0c\x63ommon.proto\"R\n\x13InitNewGroupRequest\x12\x0f\n\x07\x66or_ddp\x18\x01 \x01(\x08\x12\x0e\n\x06job_id\x18\x02 \x01(\r\x12\r\n\x05ranks\x18\x03 \x03(\r\x12\x0b\n\x03src\x18\x04 \x01(\r\"\xd4\x01\n\x12InitStandbyRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\r\x12\x10\n\x08job_name\x18\x02 \x01(\t\x12\x13\n\x0bmaster_addr\x18\x03 \x01(\t\x12\x13\n\x0bmaster_port\x18\x04 \x01(\r\x12\x0c\n\x04rank\x18\x05 \x01(\r\x12\x12\n\nlocal_rank\x18\x06 \x01(\r\x12\x12\n\nworld_size\x18\x07 \x01(\r\x12\x12\n\nbatch_size\x18\x08 \x01(\r\x12\x12\n\niterations\x18\t \x01(\r\x12\x14\n\x0c\x66rom_scratch\x18\n \x01(\x08\"H\n\x14SendOrReceiveRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\r\x12\x13\n\x0bglobal_rank\x18\x02 \x01(\r\x12\x0b\n\x03src\x18\x03 \x01(\x08\"#\n\x11KillActiveRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\r\"\x14\n\x12KillTrainerRequest2\xaf\x02\n\x0fWorkerToTrainer\x12*\n\x08NewGroup\x12\x14.InitNewGroupRequest\x1a\x06.Empty\"\x00\x12#\n\x0f\x42roadcastFinish\x12\x06.Empty\x1a\x06.Empty\"\x00\x12!\n\rTrainingBegin\x12\x06.Empty\x1a\x06.Empty\"\x00\x12,\n\x0bInitStandby\x12\x13.InitStandbyRequest\x1a\x06.Empty\"\x00\x12*\n\nKillActive\x12\x12.KillActiveRequest\x1a\x06.Empty\"\x00\x12,\n\x0bKillTrainer\x12\x13.KillTrainerRequest\x1a\x06.Empty\"\x00\x12 \n\x0cProbeTrainer\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_to_trainer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITNEWGROUPREQUEST']._serialized_start=41
  _globals['_INITNEWGROUPREQUEST']._serialized_end=123
  _globals['_INITSTANDBYREQUEST']._serialized_start=126
  _globals['_INITSTANDBYREQUEST']._serialized_end=338
  _globals['_SENDORRECEIVEREQUEST']._serialized_start=340
  _globals['_SENDORRECEIVEREQUEST']._serialized_end=412
  _globals['_KILLACTIVEREQUEST']._serialized_start=414
  _globals['_KILLACTIVEREQUEST']._serialized_end=449
  _globals['_KILLTRAINERREQUEST']._serialized_start=451
  _globals['_KILLTRAINERREQUEST']._serialized_end=471
  _globals['_WORKERTOTRAINER']._serialized_start=474
  _globals['_WORKERTOTRAINER']._serialized_end=777
# @@protoc_insertion_point(module_scope)
