# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker_to_master.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'worker_to_master.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16worker_to_master.proto\x1a\x0c\x63ommon.proto\"H\n\x15RegisterWorkerRequest\x12\x0f\n\x07ip_addr\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x10\n\x08num_gpus\x18\x03 \x01(\r\"S\n\x16RegisterWorkerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tworker_id\x18\x02 \x01(\r\x12\x15\n\rerror_message\x18\x03 \x01(\t\"0\n\x0b\x44oneRequest\x12\x11\n\tworker_id\x18\x01 \x01(\r\x12\x0e\n\x06job_id\x18\x02 \x01(\r2u\n\x0eWorkerToMaster\x12\x43\n\x0eRegisterWorker\x12\x16.RegisterWorkerRequest\x1a\x17.RegisterWorkerResponse\"\x00\x12\x1e\n\x04\x44one\x12\x0c.DoneRequest\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_to_master_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERWORKERREQUEST']._serialized_start=40
  _globals['_REGISTERWORKERREQUEST']._serialized_end=112
  _globals['_REGISTERWORKERRESPONSE']._serialized_start=114
  _globals['_REGISTERWORKERRESPONSE']._serialized_end=197
  _globals['_DONEREQUEST']._serialized_start=199
  _globals['_DONEREQUEST']._serialized_end=247
  _globals['_WORKERTOMASTER']._serialized_start=249
  _globals['_WORKERTOMASTER']._serialized_end=366
# @@protoc_insertion_point(module_scope)
